### ISSUE TITLE
Speed up docker builds locally

### ISSUE THREAD

**Issue by andygrove** [andygrove/ballista#15]
Every build of the two docker images causes all dependencies to be downloaded and compiled every time.

**Comment by igponce** [comment]
Maybe cargo --ofline might help (since we're using cargo-nightly)
Will investigate ;-)

**Comment by dbcfd** [comment]
You can also introduce a caching step, which compiles a hello world against a set of dependencies that change infrequently.

```
COPY /docker/cache/Cargo.toml /Cargo.loc[k] /build/
ADD /docker/cache/src /build/src

ARG UPDATE_DEPENDENCIES=unknown
RUN UPDATE_DEPENDENCIES=$UPDATE_DEPENDENCIES cargo update \
  && cargo build --release
```

**Comment by rrichardson** [comment]
I *think* this is where `cargo fetch` comes to the rescue. It seems it was designed exactly for this purpose.  As long as the lockfile doesn't change,  `cargo fetch` should ensure that `cargo build` never uses the network.

**Comment by dbcfd** [comment]
`cargo fetch` would require access to the cargo registry against which the lock was generated. You'd have to add that, which would make for a pretty large/long docker setup step, as well as bloating images with all dependencies in your registry.

Wouldn't be bad if you could volume during build :\

**Comment by rrichardson** [comment]
@dbcfd You're right.  It would appear that [this has been discussed](https://stackoverflow.com/a/55122453/1572175). 

Disregarding that tangent.  I do have an actual caching build working!  It's a small hack but it's not bad, actually. It is based on this advice: https://github.com/rust-lang/cargo/issues/2644#issuecomment-335272535  

My next question, probably for @andygrove  is: 
What is the motivation for https://github.com/andygrove/ballista/blob/master/examples/nyctaxi/build-docker-image.sh 
and making a new ballista directory in tmp/ballista rather than just directly depending on `../../` ?

**Comment by rrichardson** [comment]
This effectively leverages `cargo fetch` as well as building all dependencies in an "upstream" layer from the project source.  
I broke out the "platform" docker build into a separate image, so that it could be re-used by current and future examples (and 3rd party projects)
